### Artificial Neural Network Assignment - 1

### Implement Perceptron training algorithms for AND ,OR, NAND and NOR gates. 

In [10]:
import numpy as np

In [114]:
class logic_gate(object):

    def __init__(self, input_size, lr=1, epochs=100):
        self.W = np.zeros(input_size+1)
        self.epochs = epochs
        self.lr = lr
    
    def activation_fn(self, x):
        return (x >= -0.5).astype(np.float32)
 
    def predict(self, x):
        x = [1] + x
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
 
    def fit(self, X, d):
        for epoch in range(self.epochs):
            for i in range(d.shape[0]):
                x = np.insert(X[i], 0, 1)
                y = self.predict(x)
                e = d[i] - y
                self.W = self.W + self.lr * e * x

In [115]:
X_AND = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]])

D_AND = np.array([0, 0, 0, 1])

AND_gate = logic_gate(input_size=2)
AND_gate.fit(X_AND, D_AND)
print(AND_gate.W)
AND_gate.predict([0.92, 0.93])

[-4.  3.  1.]


1.0

In [127]:
X_OR = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]])

D_OR = np.array([0, 1, 1, 1])

OR_gate = logic_gate(input_size=2)
OR_gate.fit(X_OR, D_OR)
print(OR_gate.W)
OR_gate.predict([0.12, 0.93])

[-2.  1.  2.]


1.0

In [119]:
X_NAND = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]])

D_NAND = np.array([1, 1, 1, 0])

NAND_gate = logic_gate(input_size=2)
NAND_gate.fit(X_NAND, D_NAND)
print(NAND_gate.W)
NAND_gate.predict([0.91, 0.93])

[ 5. -4. -2.]


0.0

In [118]:
X_NOR = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]])

D_NOR = np.array([1, 0, 0, 0])

NOR_gate = logic_gate(input_size=2)
NOR_gate.fit(X_NOR, D_NOR)
print(NOR_gate.W)
NOR_gate.predict([0.1, 0.1])

[ 2. -2. -2.]


1.0

#### Q: How you will verify your trained algorithms? Justify your solution.

#### Justification: Our neural network gives correct output for small deviations in value. If the input is 0.1 instead of 0, or 0.92 instead of 1, the output remians correct, establishing that the neural network has learned how to classify properly.